- hosts: localhost
  become: false

  tasks:

    - name: Stop old container
      shell: |
        export PATH=$PATH:/usr/local/bin:/Applications/Docker.app/Contents/Resources/bin
        docker rm -f javacalculator || true

    - name: Pull latest image from DockerHub
      shell: |
        export PATH=$PATH:/usr/local/bin:/Applications/Docker.app/Contents/Resources/bin
        docker pull rohithsandiri/javacalculator:latest

    - name: Run container
      shell: |
        export PATH=$PATH:/usr/local/bin:/Applications/Docker.app/Contents/Resources/bin
        docker run -it \
        -p 8080:8080 \
        --name javacalculator \
        rohithsandiri/javacalculator:latest