- hosts: localhost
  become: false

  tasks:

    - name: Stop old container
      shell: /usr/local/bin/docker rm -f javacalculator || true

    - name: Pull latest image from DockerHub
      shell: /usr/local/bin/docker pull rohithsandiri/javacalculator:latest

    - name: Run container
      shell: /usr/local/bin/docker run -d --name javacalculator rohithsandiri/javacalculator:latest